# Generated by Django 6.0.7 on 2026-07-10 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "welcome_text",
                    models.TextField(
                        default="Assalomu alaykum! Jalyuzi va parda katalogimizga xush kelibsiz. 👇",
                        verbose_name="Salomlashuv matni",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Aloqa telefoni"
                    ),
                ),
                (
                    "contact_address",
                    models.TextField(blank=True, verbose_name="Manzil"),
                ),
            ],
            options={
                "verbose_name": "Bot sozlamalari",
                "verbose_name_plural": "Bot sozlamalari",
            },
        ),
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        db_index=True, unique=True, verbose_name="Telegram ID"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Username"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Ism familiya"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="Telefon raqami",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        blank=True, max_length=8, null=True, verbose_name="Til kodi"
                    ),
                ),
                (
                    "is_blocked",
                    models.BooleanField(
                        default=False,
                        help_text="Foydalanuvchi botni bloklasa, avtomatik True bo'ladi.",
                        verbose_name="Botni bloklagan",
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Birinchi tashrif"
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(auto_now=True, verbose_name="Oxirgi tashrif"),
                ),
            ],
            options={
                "verbose_name": "Foydalanuvchi",
                "verbose_name_plural": "Foydalanuvchilar",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=32, verbose_name="Telefon raqami"),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="Ko'rib chiqildi"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="catalog.product",
                        verbose_name="Mahsulot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="users.telegramuser",
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buyurtma / So'rov",
                "verbose_name_plural": "Buyurtmalar / So'rovlar",
                "ordering": ["-created_at"],
            },
        ),
    ]
